from typing import Protocol

from app.application.domain.onboarding import ApplicationRecord


class ApplicationRepositoryPort(Protocol):
    def create_application(self, application: ApplicationRecord) -> ApplicationRecord: ...

    def get_application(self, application_id: int) -> ApplicationRecord | None: ...

    def update_application(self, application: ApplicationRecord) -> None: ...

    def next_application_id(self) -> int: ...
